import { NextRequest, NextResponse } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'
import { createServerClient } from '@supabase/ssr'
import { cookies } from 'next/headers'
import { checkAndConsumeCredit } from '@/lib/credits'

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
type D = Record<string, string>

const PROMPTS: Record<string, (d: D) => string> = {
  competidores: (d) => `Eres experto en marketing digital. Identifica los 3 competidores directos más relevantes para este negocio.\n\nProducto/Servicio: ${d.producto}\nPaís: ${d.pais}\nSector: ${d.sector}\nWeb del producto: ${d.web || 'No indicada'}\n\nDevuelve SOLO JSON sin markdown:\n{"competidores":[{"nombre":"Nombre","descripcion":"Qué hacen en 1 frase","url":"web si la conoces","razon":"Por qué es competidor directo"},{"nombre":"...","descripcion":"...","url":"...","razon":"..."},{"nombre":"...","descripcion":"...","url":"...","razon":"..."}]}`,

  entorno: (d) => `Eres experto en marketing digital. Analiza el entorno para:\nPaís: ${d.pais} | Sector: ${d.sector} | Producto: ${d.producto} | Web: ${d.web||'N/A'} | Competidores: ${d.competidores||'No especificados'}\nDevuelve SOLO JSON sin markdown:\n{"situacion_pais":{"resumen":"2-3 frases contexto económico","pib_tendencia":"tendencia","variables_macro":["v1","v2","v3"],"oportunidades_pais":["op1","op2"]},"mercado":{"descripcion":"descripción 2-3 frases","tamano_estimado":"tamaño con datos","tendencia":"tendencia","players_principales":["p1","p2","p3"]},"competencia":{"analisis":"análisis 2 frases","competidores":[{"nombre":"nombre","fortaleza":"fortaleza","debilidad":"debilidad"}]},"dafo":{"oportunidades":["op1","op2","op3","op4","op5"],"amenazas":["am1","am2","am3","am4","am5"]}}`,

  target: (d) => `Eres experto en marketing. Genera target y buyer persona COMPLETO. Máximo 3 items por array.\nPaís: ${d.pais} | Sector: ${d.sector} | Producto: ${d.producto} | Web: ${d.web||'N/A'} | Tipo: ${d.tipo_negocio} | USP: ${d.usp||'No definida'}\nDevuelve SOLO JSON sin markdown:\n{"core_target":{"descripcion":"nicho más receptivo en 1 frase","sociodemografico":{"sexo":"predominante","edad":"rango","clase_social":"clase","ubicacion":"ubicación"},"volumen_estimado":"número en el país"},"broad_target":{"descripcion":"target más amplio","sociodemografico":{"sexo":"predominante","edad":"rango","clase_social":"clase"},"volumen_estimado":"número"},"buyer_persona":{"nombre":"nombre ficticio","edad":35,"profesion":"profesión","descripcion_narrativa":"Párrafo 3-4 frases en tercera persona","momentos_pensamiento":["m1","m2","m3"],"que_piensa_producto":["p1","p2","p3"],"donde_se_informa":["f1","f2","f3"],"que_escucha_mercado":["t1","t2","t3"],"que_dice":["d1","d2","d3"],"expectativas":["e1","e2","e3"],"barreras_compra":["b1","b2","b3"],"barreras_comunicacion":["c1","c2","c3"],"consumer_insight":["i1","i2","i3"]},"escalera_valor":[{"paso":1,"tipo":"TOFU","accion":"acción gratuita captación","objetivo":"objetivo"},{"paso":2,"tipo":"MOFU","accion":"acción consideración","objetivo":"objetivo"},{"paso":3,"tipo":"BOFU","accion":"acción conversión","objetivo":"objetivo"},{"paso":4,"tipo":"FIDELIZACIÓN","accion":"acción retención","objetivo":"objetivo"}]}`,

  objetivos_estimados: (d) => `Eres experto en marketing. Sugiere 3 objetivos de marketing y 3 de comunicación realistas.\n\nProducto: ${d.producto} | Sector: ${d.sector} | Presupuesto: ${d.presupuesto} | Tipo: ${d.tipo_negocio} | Fase: ${d.fase_negocio}\nTarget: ${d.target_desc||'No definido'} | USP: ${d.usp||'No definida'}\n\nDevuelve SOLO JSON sin markdown:\n{"objetivos_marketing":[{"tipo":"Marketing","kpi":"nombre KPI","dato_estimado":"número estimado","tiempo":"mes/trimestre/año","razon":"por qué este objetivo"},{"tipo":"Marketing","kpi":"...","dato_estimado":"...","tiempo":"...","razon":"..."},{"tipo":"Marketing","kpi":"...","dato_estimado":"...","tiempo":"...","razon":"..."}],"objetivos_comunicacion":[{"tipo":"Comunicación","kpi":"nombre KPI","dato_estimado":"número estimado","tiempo":"mes/trimestre/año","razon":"por qué este objetivo"},{"tipo":"Comunicación","kpi":"...","dato_estimado":"...","tiempo":"...","razon":"..."},{"tipo":"Comunicación","kpi":"...","dato_estimado":"...","tiempo":"...","razon":"..."}]}`,

  estrategia: (d) => `Eres experto en marketing digital senior con 15 años de experiencia. Crea un plan estratégico de canales completo.\n\nDATOS DEL PROYECTO:\n- País: ${d.pais} | Sector: ${d.sector} | Producto: ${d.producto}\n- Tipo negocio: ${d.tipo_negocio} | Fase: ${d.fase_negocio}\n- Presupuesto anual: ${d.presupuesto}\n- USP: ${d.usp||'No definida'} | Competidores: ${d.competidores||'No especificados'}\n- Fortalezas: ${d.fortalezas||'No definidas'}\n\nOBJETIVOS DEL PLAN:\n${d.objetivos||'No definidos'}\n\nCANALES SELECCIONADOS:\n${d.canales_seleccionados||